sudo: false
env:
  global:
    - secure: "fuGzaeyX0ar31vzAxYEpyN4wNposH6XlG3Eby6uM2TbHDgkfFpH3n4q19P7E96QYBLZCW9/teViXJbs0HVhGBCrEF5nuk40Y/JWJSPAg2/1dpGCRNRLDFtLdtNBbd8PQyGqp1PXWA9jc/zU9bmUgppmqrAlbThmKBgLZKC0cgE7hV4YWU1j+TwKaF4QjwVDqWU9UaLdZV/kcMLexBu48NQVgZPjwKpFXHeM/ZuUqBTlMQrl7FXrS/9pnvxg0sPu8VAMK1yxOWEhro67orLq37DQSLi6QLE+ltSL4EeLFAyBk166aapDsGUqHGfD8nFfYahchoVXfRkOALSYGMxDFBaFVsNrUZ4vP9mzSNU1ozC8XhmG/zm2ol32mtis6JnuAXtJ4kJBTv+ccanb+h1+1GgejqMX37Q+B978qQ6RMWW7bNzrM++sOflOwWXFZ16UPE/5SqVzxEv05tS/mygwG6O/fI+IUG6OYc7+FdmNjwSmuo2D17r46oHmpAUV0hc7QUmaFIFR2eQtbFsFNfxRnB/k+h86RLCZeECkywgoWOmd1Vu79pN1DIIkdl8hdOQbiYkHa5xE3uvNov/WGOpivB8xEA8ygtLPs1e4J6Wl3h8i8ZolbrCTJa12bNVTuNvqbdgRD9vOGP6ilYY8CbPzAIc2Fgjbkgd0ZK439ae2cnec="
    - secure: "OUbppX/YCbGHdAecOKsxlYaPWEpiMviTuw6V63zRhRFK3K5gNwI31/9dCXGPsvv5jMo3PcdflixmaiyRqVbnN9hzotQyo9pGAfaFVKVCz4bBxEuQ0g1BaWXYzII5z3AE5mZ9wn9yDv+60QA/YN0hOIksc4w5Mqo+PElUHVTlwuYi99s8gaQznqQEazzLLh8DvZGkJXijOXO0sjrvyXVquyDGkfGGggU03sDcbPBeFo1dXi0IhbBZxs6eXPtbyL9YRMYFNVl+mH6mXQR5t0HZh8R36JHY1HH6moLMCoaWc/6ERzeJmFtwfoZXp8ZSTdt7bblSFYqeLApU4kBzQM9ICaUVtq21xUXkGh95Zmb0S3vz9sgP8h7RDnKy0B4YIq32vTO0Cf27U04IwN0u/tJKGexpFFRP6VmGsaTtglbXdGzrmjZWFU+j2pGfMnNv5aLKUSZE4oiZ8kkGFhU6zfwvDH+THuOCP/FJ0kogH1CwpzP6+v48/zo9tgNv8EaNzsAb1OLV+xp9CFnkusgSQLQ2IIBCDkmrIUaee46na4Gh1ueJQ0cUr2fr/qrYqVX9OVeV0/5spvpnUT8NRe7LccyMnFWcRjLBJV4oWizElO6pQygi/7bG2fys0Nhxhx8GBj0vx9RsgYn/c4H8GpQ3u8/6jTChWnd2IJ+zzGGD+QTzNQs="

language: generic

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels bryanwweber
  - conda config --append channels conda-forge
  - conda update -q --all
  - if [[ -z "$TRAVIS_TAG" ]]; then
      conda create -q -n py35 python=3.5 pytest pytest-cov coolprop pint;
      conda create -q -n py36 python=3.6 pytest pytest-cov coolprop pint;
    else
      conda install -q conda-build anaconda-client;
    fi
  - conda info -a
  - conda list

script:
  - set -e
  - if [[ -z "$TRAVIS_TAG" ]]; then
      source activate py35;
      pytest -vv --cov=./ --cov-append;
      source activate py36;
      pytest -vv --cov=./ --cov-append;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        conda install -q sphinx doctr nbsphinx ipython ipykernel pandoc;
        python setup.py install;
        cd docs;
        make html SPHINXOPTS="-W";
        cd ..;
        doctr deploy .;
      fi
    else
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        conda build conda.recipe;
        anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/*/thermostate*.tar.bz2;
      fi
    fi
  - set +e

after_success:
  - if [[ -z "$TRAVIS_TAG" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi

before_deploy:
  - conda install pandoc pypandoc

deploy:
  provider: pypi
  user: bryanwweber
  password:
    secure: "unjgvppcriMzBPwzvaDeohcXByNsXuqoR5GvAFuqxXbqLLHvnPQrNx+/HvTDb9GJ5akHYbQFjQv1nSgKQWKKYMfzgRFbeYxWmgVHzm+uX41znMeMs9c6/0wd0K8EgcNKMsw+Xz56yfudoE0hceP49uPOjgCsqx6MqHsN9kWgy9JkGgedI2W9TpkGlj7IFwTnisDgF+3XcbCbp0xIcRgaB8TjP4vU4kf3lRHivOC8vywEFLmYBOg1sMSawHXnubAUNJmj4jGEsef0aZB7/LetIwBhxgKS9PiwzOOVnLoteit+cyIFil4/3ulyQ3ZUYV35dGR/DiPJA17K74MBrhcnS4es4l6l7WhGhRkCrYAdMeYvv1o1ueuTfnXEYq9/hzTt13llCt5458P5bV1CbRSgOfROl5Euf4fQWvSWZQPx21cnqDjYs4KJat/4+f8maLuf2MIKA5EIxo3CIzVSUiAU57uaBgbvlW/7ZUa4FOmTs5tGVpm185NiFAvfoRQx9Ue0E8Hi7i/SqT+03RzUqsi/nbsPlKjbFk8Hb8SiqVn/aSNyPw7lmSsVOYntvUQggti+ZSehj5QbWHxK3fXJlAm9j9/Mft+PdNESZ8MPUrCuXYaF2r9O0ZYew1f3AyTwSYsvh0cd1W/ADLu7PNKpiJI/ONmEZCF9yEP9TW1Ax4i9G4w="
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "linux"
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
